Table.SelectRows(Issues, each Text.StartsWith([Title], "["))
