table Date
	lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: b2c3d4e5-f6a7-8901-bcde-f12345678901
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: c3d4e5f6-a7b8-9012-cdef-123456789012
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: d4e5f6a7-b8c9-0123-defa-234567890123
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		lineageTag: e5f6a7b8-c9d0-1234-efab-345678901234
		summarizeBy: none
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: f6a7b8c9-d0e1-2345-fabc-456789012345
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition Date = m
		mode: import
		source =
				let
				    StartDate = #date(2013, 1, 1),
				    EndDate = #date(2015, 12, 31),
				    DateList = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1, 0, 0, 0)),
				    #"Converted to Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Month" = Table.AddColumn(#"Added Year", "Month", each Date.ToText([Date], "MMM"), type text),
				    #"Added Month Number" = Table.AddColumn(#"Added Month", "Month Number", each Date.Month([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Month Number", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text)
				in
				    #"Added Quarter"

	annotation PBI_ResultType = Table

