authors:
  justinmartin:
    name: Justin Martin
    description: Just a guy who really likes Power BI.
    avatar: https://daxnoobjustin.github.io/daxnoob.github.io/assets/images/avatar.png
    url: https://www.linkedin.com/in/daxnoobjustin/
    email: justin@daxnoob.blog
